global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']

  - job_name: 'services'
    static_configs:
      # Add service metrics ports here; we'll expose 9100 on each Node service
      - targets: ['api-gateway:9100', 'donation-service:9100', 'payment-service:9100', 'notification-service:9100']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
